// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.message.hello;

public final class HelloOuterClass {
  private HelloOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_message_hello_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_message_hello_Hello_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\036com.zpb.protobuf.message." +
      "hello\"?\n\005Hello\022\n\n\002id\030\001 \001(\003\022\013\n\003age\030\002 \001(\005\022" +
      "\014\n\004name\030\003 \001(\t\022\017\n\007address\030\004 \001(\tB\005P\001\240\001\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zpb_protobuf_message_hello_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_protobuf_message_hello_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_message_hello_Hello_descriptor,
        new java.lang.String[] { "Id", "Age", "Name", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
